version: "3.9"

services:

  grievance-ai:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: grievance-ai-system

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./reports:/app/reports

    environment:
      - PYTHONUNBUFFERED=1

    restart: unless-stopped